#spring.application.name=ServiceRegistry

#here in this  code  in client we have done  two thing false because   we  want  then  not  not  register   this  as  a  client


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 1111